<?php
declare(strict_types=1);

return [
    '@PHP80Migration:risky' => true,
    '@PHP81Migration' => true,
    '@PSR12' => true,
    '@PSR12:risky' => true,
    '@Symfony' => true,
    '@Symfony:risky' => true,
    'blank_line_after_namespace' => true,
    'blank_line_after_opening_tag' => false,
    'class_keyword' => true,
    'clean_namespace' => true,
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'compact_nullable_type_declaration' => true,
    'concat_space' => ['spacing' => 'one'],
    'control_structure_continuation_position' => true,
    'fully_qualified_strict_types' => true,
    'global_namespace_import' => [
        'import_classes' => false,
        'import_constants' => false,
        'import_functions' => false,
    ],
    'heredoc_indentation' => ['indentation' => 'same_as_start'],
    'increment_style' => ['style' => 'post'],
    'list_syntax' => ['syntax' => 'short'],
    'mb_str_functions' => true,
    'method_argument_space' => [
        'on_multiline' => 'ensure_fully_multiline',
    ],
    'native_function_invocation' => [
        'exclude' => [],
        'include' => ['@all'],
        'scope' => 'all',
    ],
    'new_with_parentheses' => true,
    'no_empty_comment' => true,
    'no_unused_imports' => true,
    'no_useless_else' => true,
    'no_useless_return' => true,
    'nullable_type_declaration' => ['syntax' => 'union'],
    'nullable_type_declaration_for_default_null_value' => true,
    'ordered_imports' => true,
    'phpdoc_line_span' => ['const' => 'single', 'method' => 'single', 'property' => 'single'],
    'phpdoc_order' => true,
    'phpdoc_summary' => false,
    'phpdoc_to_comment' => ['ignored_tags' => ['var', 'phpstan-var']],
    'single_import_per_statement' => true,
    'single_line_comment_style' => ['comment_types' => ['hash']],
    'single_line_throw' => false,
    'static_lambda' => true,
    'strict_comparison' => true,
    'strict_param' => true,
    'ternary_to_null_coalescing' => true,
    'trailing_comma_in_multiline' => [
        'after_heredoc' => true,
        'elements' => ['arguments', 'array_destructuring', 'arrays', 'match', 'parameters'],
    ],
    'types_spaces' => [
        'space_multiple_catch' => 'single',
    ],
];
